apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::988212813982:role/nodegroup-InstanceRole-1NRDD0R220DDT
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: | 
    - userarn: arn:aws:iam::759288920914:user/udacity1 
      username: designated_user 
      groups: 
        - system:masters