apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-capstone
  labels:
    app: project-capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: project-capstone
    spec:
      containers:
        - image: iancrowl/project-capstone
          imagePullPolicy: Always
          name: project-capstone
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: project-capstone
  labels:
    app: project-capstone
spec:
  type: LoadBalancer
  selector:
    app: project-capstone
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
      protocol: TCP
