apiVersion: v1
kind: Service
metadata:
  name: project-capstone
  labels:
    app: project-capstone
spec:
  type: LoadBalancer
  selector:
    app: project-capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
